server:
  port: 8762
spring:
  application:
    name: chapter_client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/chapter_server/eureka/
